version: "3"

services: 
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web 
  web:
    build: .
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./:/usr/src/app/
      - media_volume:/usr/src/app/media
    expose: 
      - 8000
    env_file:
      - ./.env.production
volumes: 
  media_volume: